DROP TABLE IF EXISTS support_admin_audit;
DROP TABLE IF EXISTS support_status_history;
DROP TABLE IF EXISTS support_messages;
DROP TABLE IF EXISTS support_requests;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS ai_usage_logs;
DROP TABLE IF EXISTS memory_entries;
DROP TABLE IF EXISTS conversations;
DROP TABLE IF EXISTS user_zeroon_companions;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS state_sessions;
DROP TABLE IF EXISTS zero_records;
DROP TABLE IF EXISTS state_history;
DROP TABLE IF EXISTS refresh_sessions;
DROP TABLE IF EXISTS prompt_templates;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid VARCHAR(32) NOT NULL UNIQUE,
    mobile VARCHAR(20) UNIQUE,
    email VARCHAR(100) UNIQUE,
    nickname VARCHAR(50),
    avatar VARCHAR(500),
    current_state VARCHAR(20) NOT NULL DEFAULT 'CALM',
    continuous_days INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    language_preference VARCHAR(20) NOT NULL DEFAULT 'FOLLOW_SYSTEM'
        CHECK (language_preference IN ('FOLLOW_SYSTEM', 'ZH_CN', 'EN')),
    deletion_requested_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    device_id VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    nickname VARCHAR(30),
    avatar_preset VARCHAR(30),
    age_range VARCHAR(20),
    occupation VARCHAR(40),
    self_description VARCHAR(120),
    ai_profile_context_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_zeroon_companions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    companion_key VARCHAR(30) NOT NULL,
    display_name VARCHAR(30),
    nameplate_serial VARCHAR(20) NOT NULL UNIQUE,
    met_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE state_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    previous_state VARCHAR(20),
    current_state VARCHAR(20) NOT NULL,
    source VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE zero_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    state VARCHAR(20) NOT NULL,
    goal CLOB,
    content CLOB,
    ai_summary CLOB,
    state_session_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE state_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    state VARCHAR(20) NOT NULL,
    source VARCHAR(20) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    ended_by_record_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content CLOB NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    safety_label VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE memory_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(255),
    summary CLOB NOT NULL,
    importance SMALLINT NOT NULL DEFAULT 1,
    source_type VARCHAR(30),
    source_id BIGINT,
    expires_at TIMESTAMP WITH TIME ZONE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ai_context_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((source_type IS NULL) = (source_id IS NULL)),
    UNIQUE (user_id, source_type, source_id, type)
);

CREATE TABLE prompt_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    content CLOB NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (code, version)
);

CREATE TABLE ai_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100),
    operation VARCHAR(50) NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    duration_ms INTEGER NOT NULL,
    prompt_template_code VARCHAR(100),
    prompt_template_version INTEGER,
    input_chars INTEGER NOT NULL DEFAULT 0,
    output_chars INTEGER NOT NULL DEFAULT 0,
    input_tokens INTEGER CHECK (input_tokens IS NULL OR input_tokens >= 0),
    output_tokens INTEGER CHECK (output_tokens IS NULL OR output_tokens >= 0),
    error_code VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE support_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    public_reference VARCHAR(32) NOT NULL UNIQUE,
    client_submission_id VARCHAR(36) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    category VARCHAR(30) NOT NULL CHECK (category IN (
        'PRODUCT_PROBLEM', 'SUGGESTION', 'ACCOUNT_DATA_PRIVACY',
        'AI_RESPONSE_SAFETY', 'COMPLAINT_RIGHTS', 'OTHER'
    )),
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED' CHECK (status IN (
        'RECEIVED', 'IN_REVIEW', 'WAITING_FOR_USER', 'REPLIED', 'CLOSED'
    )),
    subject VARCHAR(120) NOT NULL,
    description CLOB NOT NULL,
    reply_contact VARCHAR(200),
    diagnostic_app_version VARCHAR(40),
    diagnostic_build VARCHAR(40),
    diagnostic_platform VARCHAR(30),
    diagnostic_os_family VARCHAR(40),
    diagnostic_locale VARCHAR(10) CHECK (
        diagnostic_locale IS NULL OR diagnostic_locale IN ('zh-CN', 'en')
    ),
    diagnostic_error_code VARCHAR(80),
    diagnostic_timestamp TIMESTAMP WITH TIME ZONE,
    assigned_admin_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    escalated BOOLEAN NOT NULL DEFAULT FALSE,
    escalation_code VARCHAR(40) CHECK (
        (escalated = FALSE AND escalation_code IS NULL)
        OR
        (escalated = TRUE AND escalation_code IN (
            'ENGINEERING', 'PRODUCT', 'PRIVACY', 'SAFETY',
            'COMPLAINT', 'PROFESSIONAL_REVIEW'
        ))
    ),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    UNIQUE (user_id, client_submission_id)
);

CREATE INDEX idx_support_requests_user_created
    ON support_requests (user_id, created_at);

CREATE TABLE support_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES support_requests(id) ON DELETE CASCADE,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_type VARCHAR(20) NOT NULL CHECK (actor_type IN ('SYSTEM', 'USER', 'ADMIN')),
    visibility VARCHAR(20) NOT NULL CHECK (visibility IN ('USER_VISIBLE', 'INTERNAL')),
    body CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE support_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES support_requests(id) ON DELETE CASCADE,
    from_status VARCHAR(30) CHECK (
        from_status IS NULL OR from_status IN (
            'RECEIVED', 'IN_REVIEW', 'WAITING_FOR_USER', 'REPLIED', 'CLOSED'
        )
    ),
    to_status VARCHAR(30) NOT NULL CHECK (to_status IN (
        'RECEIVED', 'IN_REVIEW', 'WAITING_FOR_USER', 'REPLIED', 'CLOSED'
    )),
    actor_type VARCHAR(20) NOT NULL CHECK (actor_type IN ('SYSTEM', 'USER', 'ADMIN')),
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reason_code VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE support_admin_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES support_requests(id) ON DELETE CASCADE,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action_type VARCHAR(30) NOT NULL CHECK (action_type IN (
        'CATEGORY_CHANGE', 'ASSIGNMENT_CHANGE', 'ESCALATION_CHANGE',
        'STATUS_CHANGE', 'USER_VISIBLE_REPLY', 'INTERNAL_NOTE'
    )),
    from_value VARCHAR(100),
    to_value VARCHAR(100),
    message_id BIGINT REFERENCES support_messages(id) ON DELETE SET NULL,
    reason_code VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
