ALTER TABLE evidence_events
    DROP CONSTRAINT IF EXISTS chk_evidence_event_name;

ALTER TABLE evidence_events
    ADD CONSTRAINT chk_evidence_event_name CHECK (event_name IN (
        'AUTH_COMPLETED', 'ZEROON_ENCOUNTER_VIEWED',
        'ZEROON_ENCOUNTER_COMPLETED', 'STATE_STARTED', 'RESET_STARTED',
        'RECORD_SAVED', 'RECORD_SAVE_FAILED', 'ARCHIVE_VIEWED',
        'RECORD_DETAIL_VIEWED', 'RETURN_CUE_AVAILABLE', 'RETURN_CUE_OPENED',
        'RETURN_CUE_DISMISSED', 'RETURN_CUE_CONTINUED', 'REFLECTION_REQUESTED',
        'REFLECTION_COMPLETED', 'MEMORY_CONTROL_CHANGED',
        'PROFILE_AI_CONTEXT_CHANGED', 'PROFILE_AI_CONTEXT_CONTROL_VIEWED',
        'DATA_EXPORT_REQUESTED', 'ACCOUNT_DELETE_REQUESTED'
    ));
